Update kopijahe

diff --git a/scripts/kopijahe b/scripts/kopijahe
--- a/scripts/kopijahe
+++ b/scripts/kopijahe
@@ -17,7 +17,7 @@ touch /etc/config/kopijahe
 versi() {
 	# Fungsi versi aplikasi
 	# Tentukan versi dengan mengubah variabel "ver"
-	ver="1.9.7"
+	ver="1.9.6"
 }
 
 bantuan() {
@@ -67,11 +67,11 @@ bantuan() {
 	echo "kopijahe -m 1 -l \"yes\" -u \"halo@kopijahe.my.id\" -p \"en4kbang3t\" -v \"smartbisnis\" -a" 
 	echo "kopijahe -m 2 -l \"yes\" -u \"hola@kopijahe.my.id\" -p \"n1kmats3kali\" -v \"smartbisnis\" -a"
 	echo ""
-	echo "Penggunaan untuk 1 auto-reconnect seamless (diletakkan di berkas /etc/rc.local):"
-	echo "kopijahe -s"
+	echo "Penggunaan untuk 1 auto-reconnect seamless:"
+	echo "kopijahe -l \"no\" -s"
 	echo ""
-	echo "Penggunaan dengan berkas tangkapan login CURL (login_file.txt) via Google Chrome (diletakkan di berkas /etc/rc.local):"
-	echo "kopijahe -f \"/etc/login_file.txt\""
+	echo "Penggunaan dengan berkas tangkapan login CURL via Google Chrome (login_file.txt):"
+	echo "kopijahe -l \"no\" -f \"/etc/login_file.txt\""
 	echo ""
 	echo "Login manual jika autologin gagal (untuk keperluan analisa jika gagal autologin):"
 	echo "kopijahe -x -z"
@@ -421,8 +421,6 @@ testing() {
 
 cpctesting() {
 	# Mode testing penyedia jasa cek koneksi
-	cpcretry="1"
-	cpctimeout="1"
 	
 	echo "Tes penyedia jasa layanan cek koneksi"
 	cpcprovider="kopijahe"
@@ -461,10 +459,6 @@ captiveportalcheck() {
 	if [[ "$advancedmode" != "true" ]]; then
 		# Tentukan penyedia layanan cek captive portal berdasarkan konfigurasi sebelumnya
 		cpcprovider="$(uci -q get kopijahe.@autologin["$multiautologinnum"].cpcprovider)"
-		# Jumlah percobaan ulang cek captive portal
-		cpcretry="$(uci -q get kopijahe.@autologin["$multiautologinnum"].cpcretry)"
-		# Lama timeout cek captive portal
-		cpctimeout="$(uci -q get kopijahe.@autologin["$multiautologinnum"].cpctimeout)"
 	fi
 	
 	# Jika konfigurasi tidak ditemukan, maka:
@@ -477,6 +471,9 @@ captiveportalcheck() {
 		cpcprovider="kopijahe"
 	fi
 	
+	# Jumlah percobaan ulang cek captive portal
+	cpcretry="$(uci -q get kopijahe.@autologin["$multiautologinnum"].cpcretry)"
+	
 	#	Jika konfigurasi tidak ditemukan, maka:
 	if [[ "$cpcretry" = "" ]]; then
 		# Masukkan konfigurasi bawaan percobaan ulang 2 kali
@@ -486,6 +483,9 @@ captiveportalcheck() {
 		# Tentukan variabel cpcretry ke 2
 		cpcretry="2"
 	fi
+	
+	# Lama timeout cek captive portal
+	cpctimeout="$(uci -q get kopijahe.@autologin["$multiautologinnum"].cpctimeout)"
 	
 	# Jika konfigurasi tidak ditemukan, maka:
 	if [[ "$cpctimeout" = "" ]]; then
@@ -502,46 +502,55 @@ captiveportalcheck() {
 	# KopiJahe: Layanan cek captive portal bawaan script
 	if [[ "$cpcprovider" = "kopijahe" ]]; then
 		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://periksakoneksi.kopijahe.my.id/cek")"
+    server="208.67.222.222"
 		kodestatuslanding="$?"
 		hasil="OK"
 	# Firefox: Layanan cek captive portal bawaan browser Mozilla Firefox
 	elif [[ "$cpcprovider" = "firefox" ]]; then
 		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://detectportal.firefox.com/success.txt")"
+    server="208.67.220.220"
 		kodestatuslanding="$?"
 		hasil="success"
 	# Google: Layanan cek captive portal bawaan sistem operasi android
 	elif [[ "$cpcprovider" = "google" ]]; then
 		cekkoneksi="$(curl --interface "$wandevice" -LI --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://connectivitycheck.gstatic.com/generate_204" | grep -o "204")"
+    server="8.8.4.4"
 		kodestatuslanding="$?"
 		hasil="204"
 	# Google2: Layanan cek captive portal bawaan chrome
 	elif [[ "$cpcprovider" = "google2" ]]; then
 		cekkoneksi="$(curl --interface "$wandevice" -LI --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://clients3.google.com/generate_204" | grep -o "204")"
+    server="8.8.8.8"
 		kodestatuslanding="$?"
 		hasil="204"
 	# Apple: Layanan cek captive portal bawaan perangkat Apple
 	elif [[ "$cpcprovider" = "apple" ]]; then
 		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://captive.apple.com/" | grep -o "Success" | head -c8)"
+    server="1.1.1.2"
 		kodestatuslanding="$?"
 		hasil="Success"
 	# Apple2: Layanan cek captive portal alternatif perangkat Apple
 	elif [[ "$cpcprovider" = "apple2" ]]; then
 		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "https://www.apple.com/library/test/success.html" | grep -o "Success" | head -c8)"
+    server="1.0.0.1"
 		kodestatuslanding="$?"
 		hasil="Success"
 	# Microsoft2: Layanan cek captive portal alternatif milik Microsoft
 	elif [[ "$cpcprovider" = "microsoft2" ]]; then
 		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://www.msftncsi.com/ncsi.txt")"
+    server="4.4.4.4"
 		kodestatuslanding="$?"
 		hasil="Microsoft NCSI"
 	# Microsoft: Layanan cek captive portal bawaan sistem operasi Windows
 	elif [[ "$cpcprovider" = "microsoft" ]]; then
 		cekkoneksi="$(curl --interface "$wandevice" -L --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://www.msftconnecttest.com/connecttest.txt")"
+    server="9.9.9.9"
 		kodestatuslanding="$?"
 		hasil="Microsoft Connect Test"
 	# Xiaomi: Layanan cek captive portal bawaan sistem operasi MIUI
 	elif [[ "$cpcprovider" = "xiaomi" ]]; then
 		cekkoneksi="$(curl --interface "$wandevice" -LI --silent --retry $cpcretry --max-redirs 1 --connect-timeout $cpctimeout "http://connect.rom.miui.com/generate_204" | grep -o "204")"
+    server="94.140.14.14"
 		kodestatuslanding="$?"
 		hasil="204"
 	fi
@@ -553,9 +562,18 @@ captiveportalcheck() {
 		cpcstatus="Sukses"
 	# Jika hasilnya tidak sama, maka:
 	else
-		# Tentukan bahwa tidak terkoneksi dengan internet
+    # Lakukan uji ping ke server dulu sebelum memastikan koneksi down
+    testping="$(ping -I "$wandevice" $server -c 2)"
+    testping="$?"
+    if [[ "$testping" -eq 1 ]]; then
+    # Tentukan bahwa terkoneksi dengan internet
+		internetconnected="yes"
+		cpcstatus="Sukses"
+    else
+    # Tentukan bahwa tidak terkoneksi dengan internet
 		internetconnected="no"
 		cpcstatus="Gagal"
+    fi
 	fi	
 	
 	# Jika kode status hasil cek koneksi adalah 127, maka:
@@ -898,9 +916,7 @@ do
 				exit 0
 			else
 				echo "Penyedia layanan yang didukung:"
-				echo "\"kopijahe\" (default), \"firefox\", \"google\", \"google2\", \"apple\", \"apple2\", \"microsoft\", \"microsoft2\", \"xiaomi\""
-				echo ""
-				echo "Untuk menguji penyedia layanan yang bisa dipakai, bisa menggunakan -c test"
+				echo "\"kopijahe\" (default), \"firefox\", \"google\", \"apple\", \"microsoft\", \"xiaomi\""
 				exit 1
 			fi
 			uci commit kopijahe
@@ -975,6 +991,9 @@ do
 			uci set kopijahe.@autologin["$multiautologinnum"].username="$username"
 			uci commit kopijahe
 			;;
+		\?)
+			bantuan
+			;;
 		v)
 			wifivariant="$OPTARG"
 			advancedmode="true"
@@ -1013,14 +1032,12 @@ do
 			detectwan
 			login_wifi
 			;; 
-		\?)
-			bantuan
-			;;
 		:)
-			echo "perintah tidak diketahui atau salah"
+			echo "invalid"
 			exit 1
 			;;
 		*)
+			autologin
 			;;
 	esac
 done
